/**
 * RouteSelectionModal.js  (updated)
 *
 * Changes from previous version:
 *  1. Route header shows "{First Stop} → {Last Stop}" (unchanged).
 *  2. Inline editable name field (unchanged).
 *  3. When a route has faresFromDB=true (generated by DB Composite Only mode),
 *     all fare inputs are pre-filled and visually marked as "from DB" (green).
 *  4. Individual fare inputs that have a value already show a green "✓ DB fare" badge.
 *  5. New prop: onFindExistingFare — async (stopA_id, stopB_id) => fare|null,
 *     called lazily when a fare field is blank but stops are known.
 */

import React, { useEffect, useRef } from 'react';
import { ArrowLeft, Check, X, Route, Edit2, Database, Info } from 'lucide-react';

/* ─────────────────────────────────────────────────────────────────
   Single fare input row — shows a "DB" badge when value came from DB
───────────────────────────────────────────────────────────────── */
const FareInputRow = ({ fromLabel, toLabel, value, onChange, fromDB }) => (
  <div className="fare-input-row">
    <span className="fare-label" style={{ flex: 1 }}>
      {fromLabel} → {toLabel}
    </span>
    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
      {fromDB && value && (
        <span
          style={{
            fontSize: '10px',
            fontWeight: 700,
            background: '#dcfce7',
            color: '#15803d',
            border: '1px solid #86efac',
            borderRadius: '10px',
            padding: '2px 7px',
            whiteSpace: 'nowrap',
          }}
        >
          <Database size={9} style={{ marginRight: 2 }} />
          DB
        </span>
      )}
      <input
        className="fare-input-small"
        placeholder="GH₵ 0.00"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        type="number"
        step="0.01"
        style={
          fromDB && value
            ? { borderColor: '#86efac', background: '#f0fdf4' }
            : {}
        }
      />
    </div>
  </div>
);

/* ─────────────────────────────────────────────────────────────────
   Main modal
───────────────────────────────────────────────────────────────── */
const RouteSelectionModal = ({
  visible,
  foundRoutes,
  selectedRoutes,
  onRouteToggle,
  onFareChange,
  onSaveRoutes,
  onCancel,
  isLoading,
  onAddReverseRoute,
  onCloseReverseRoute,
  currentPage,
  routesPerPage,
  onLoadMore,
  hasMoreRoutes,
  onRoutesPerPageChange,
  routeNames,
  onRouteNameChange,
}) => {
  if (!visible) return null;

  const getRouteTypeLabel = (type) => {
    switch (type) {
      case 'auto_composite':              return '🔗 Auto Composite';
      case 'direct':
      case 'direct_with_station':         return 'Direct Route';
      case '1_intermediate':
      case '1_intermediate_with_station': return '1 Stop Route';
      case '2_intermediate':
      case '2_intermediate_with_station': return '2 Stop Route';
      case '3_intermediate':
      case '3_intermediate_with_station': return '3 Stop Route';
      default:
        if (type?.includes('direct'))       return 'Direct Route';
        if (type?.includes('intermediate')) {
          const count = type.match(/\d+/)?.[0] || '?';
          return `${count} Stop Route`;
        }
        return 'Standard Route';
    }
  };

  const hasStation = (type) => type?.includes('_with_station');

  const defaultName = (route) =>
    route?.stops?.length >= 2
      ? `${route.stops[0].name} to ${route.stops[route.stops.length - 1].name}`
      : '';

  const getDisplayName = (route, index) =>
    routeNames?.[index] != null ? routeNames[index] : defaultName(route);

  const currentRoutes = foundRoutes.slice(0, (currentPage + 1) * routesPerPage);

  // Count how many routes have all fares from DB
  const dbFareCount = foundRoutes.filter(r => r.faresFromDB).length;

  return (
    <div className="modal-overlay">
      <div className="modal-container large-modal">

        {/* ── Header ── */}
        <div className="modal-header sticky-header">
          <button className="back-button" onClick={onCancel}>
            <ArrowLeft size={24} />
          </button>
          <h2 className="modal-title">
            Select Routes ({foundRoutes.length} found, showing {currentRoutes.length})
          </h2>
          <div style={{ width: 24 }} />
        </div>

        {/* ── DB fares notice ── */}
        {dbFareCount > 0 && (
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              background: '#f0fdf4',
              border: '1px solid #86efac',
              borderRadius: '10px',
              padding: '10px 14px',
              margin: '0 0 12px',
              fontSize: '13px',
              color: '#15803d',
            }}
          >
            <Database size={16} color="#16a34a" style={{ flexShrink: 0 }} />
            <span>
              <strong>{dbFareCount} route{dbFareCount !== 1 ? 's' : ''}</strong> have fares
              pre-filled from your routes table — shown with a green{' '}
              <span
                style={{
                  fontSize: '10px', fontWeight: 700,
                  background: '#dcfce7', color: '#15803d',
                  border: '1px solid #86efac', borderRadius: '10px',
                  padding: '1px 6px',
                }}
              >
                DB
              </span>{' '}
              badge. You can still edit them before saving.
            </span>
          </div>
        )}

        {/* ── Batch size selector ── */}
        <div className="batch-size-selector">
          <label className="batch-size-label">Show per batch:</label>
          <select
            className="batch-size-select"
            value={routesPerPage}
            onChange={(e) => onRoutesPerPageChange(parseInt(e.target.value))}
          >
            <option value={20}>20 routes</option>
            <option value={50}>50 routes</option>
            <option value={100}>100 routes</option>
          </select>
          <span className="batch-info">
            Page {currentPage + 1} • Showing{' '}
            {Math.min((currentPage + 1) * routesPerPage, foundRoutes.length)} of{' '}
            {foundRoutes.length}
          </span>
        </div>

        {/* ── Sticky action bar ── */}
        <div className="modal-actions-sticky">
          <div className="selected-count">{selectedRoutes.length} route(s) selected</div>
          <div className="sticky-buttons">
            <button className="cancel-button" onClick={onCancel}>
              Cancel
            </button>
            <button
              className={`save-button ${isLoading ? 'save-button-disabled' : ''}`}
              onClick={onSaveRoutes}
              disabled={isLoading || selectedRoutes.length === 0}
            >
              {isLoading ? <div className="spinner" /> : `Save ${selectedRoutes.length}`}
            </button>
          </div>
        </div>

        {/* ── Route list ── */}
        <div className="modal-content-with-sticky">
          {currentRoutes.map((route, index) => {
            const displayName  = getDisplayName(route, index);
            const isSelected   = selectedRoutes.includes(index);
            const allFromDB    = route.faresFromDB === true;

            return (
              <div key={route.id || index} className="route-option-container">

                {/* ── Checkbox + route summary ── */}
                <button className="route-checkbox" onClick={() => onRouteToggle(index)}>
                  <div className={`checkbox ${isSelected ? 'checkbox-selected' : ''}`}>
                    {isSelected && <Check size={16} color="#fff" />}
                  </div>

                  <div className="route-header-info">
                    <span className="route-option-title">
                      {displayName}
                      {hasStation(route.type) && (
                        <span className="route-type-with-station">🚍 Station</span>
                      )}
                      {route.isDuplicate && (
                        <span className="duplicate-badge"> Duplicate</span>
                      )}
                      {route.hasSubRoutes && (
                        <span className="subroute-badge">🔗 Sub-routes</span>
                      )}
                      {allFromDB && (
                        <span
                          style={{
                            marginLeft: '6px',
                            fontSize: '10px', fontWeight: 700,
                            background: '#dcfce7', color: '#15803d',
                            border: '1px solid #86efac',
                            borderRadius: '10px', padding: '2px 7px',
                            verticalAlign: 'middle',
                          }}
                        >
                          <Database size={9} style={{ marginRight: 2 }} />
                          Fares from DB
                        </span>
                      )}
                    </span>

                    <span className="route-type">
                      {getRouteTypeLabel(route.type)} &nbsp;•&nbsp; {route.totalDistance} km
                      {route.stops.length > 2 && (
                        <>
                          {' '}&nbsp;•&nbsp; {route.stops.length - 2} intermediate{' '}
                          {route.stops.length - 2 === 1 ? 'stop' : 'stops'}
                        </>
                      )}
                    </span>
                  </div>
                </button>

                {/* ── Expanded panel when selected ── */}
                {isSelected && (
                  <div className="fare-section">

                    {/* Editable name field */}
                    <div
                      style={{
                        display: 'flex', alignItems: 'center', gap: '8px',
                        marginBottom: '12px', background: '#f9fafb',
                        border: '1px solid #e5e7eb', borderRadius: '8px',
                        padding: '8px 12px',
                      }}
                    >
                      <Edit2 size={14} color="#6b21a8" style={{ flexShrink: 0 }} />
                      <input
                        style={{
                          flex: 1, border: 'none', background: 'transparent',
                          fontSize: '13px', fontWeight: 500, color: '#111827', outline: 'none',
                        }}
                        value={displayName}
                        onChange={(e) => onRouteNameChange(index, e.target.value)}
                        placeholder="Route name…"
                      />
                      {routeNames?.[index] != null && (
                        <button
                          type="button"
                          title="Reset to auto-generated name"
                          style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            color: '#9ca3af', padding: '2px', lineHeight: 1,
                          }}
                          onClick={() => onRouteNameChange(index, null)}
                        >
                          <X size={13} />
                        </button>
                      )}
                    </div>

                    {/* Fare inputs header */}
                    <div className="fare-section-header">
                      <span className="fare-section-title">
                        {allFromDB ? (
                          <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                            <Database size={13} color="#16a34a" />
                            Fares (pre-filled from DB — editable):
                          </span>
                        ) : (
                          'Set Fares:'
                        )}
                      </span>
                      <div className="fare-section-actions">
                        {!route.reverseRoute ? (
                          <button
                            className="reverse-route-button"
                            onClick={() => onAddReverseRoute(index)}
                          >
                            <Route size={16} />
                            Add Reverse Route
                          </button>
                        ) : (
                          <button
                            className="close-reverse-route-button"
                            onClick={() => onCloseReverseRoute(index)}
                          >
                            <X size={16} />
                            Remove Reverse
                          </button>
                        )}
                      </div>
                    </div>

                    {/* Fare rows for main route */}
                    {route.stops.map(
                      (stop, stopIndex) =>
                        stopIndex < route.stops.length - 1 && (
                          <FareInputRow
                            key={stopIndex}
                            fromLabel={stop.name}
                            toLabel={route.stops[stopIndex + 1].name}
                            value={route.fares[stopIndex]}
                            onChange={(v) => onFareChange(index, stopIndex, v)}
                            fromDB={allFromDB && !!route.fares[stopIndex]}
                          />
                        ),
                    )}

                    {/* Reverse route section */}
                    {route.reverseRoute && (
                      <div className="reverse-route-section">
                        <div className="reverse-route-header">
                          <h4 className="reverse-route-title">Reverse Route</h4>
                          <button className="close-reverse-button" onClick={() => onCloseReverseRoute(index)}>
                            <X size={14} />
                          </button>
                        </div>
                        {route.reverseRoute.stops.map(
                          (stop, stopIndex) =>
                            stopIndex < route.reverseRoute.stops.length - 1 && (
                              <div key={stopIndex} className="fare-input-row reverse">
                                <span className="fare-label">
                                  {stop.name} → {route.reverseRoute.stops[stopIndex + 1].name}
                                </span>
                                <input
                                  className="fare-input-small"
                                  placeholder="GH₵ 0.00"
                                  value={route.reverseRoute.fares[stopIndex]}
                                  onChange={(e) => onFareChange(index, stopIndex, e.target.value, true)}
                                  type="number"
                                  step="0.01"
                                />
                              </div>
                            ),
                        )}
                      </div>
                    )}
                  </div>
                )}

                {/* Stop path preview */}
                <span className="route-path">
                  {route.stops.map((s) => s.name).join(' → ')}
                </span>
              </div>
            );
          })}
        </div>

        {/* ── Load more ── */}
        {hasMoreRoutes && (
          <div className="load-more-section">
            <button
              className="load-more-button"
              onClick={onLoadMore}
              disabled={isLoading}
            >
              {isLoading ? (
                <div className="spinner" />
              ) : (
                <>
                  <ArrowLeft size={20} className="load-more-icon" />
                  Load Next{' '}
                  {Math.min(routesPerPage, foundRoutes.length - currentRoutes.length)} Routes
                  <ArrowLeft size={20} className="load-more-icon" />
                </>
              )}
            </button>
            <div className="progress-text">
              Showing {currentRoutes.length} of {foundRoutes.length} routes
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default RouteSelectionModal;